
use strict;
use warnings;

use Test::Cmd;

# Some basic tests.

use lib './module';
use Initfour::Backoffice;
use Initfour::Backoffice::System;


sub diff {
	my ($file1, $file2) = @_;
	$file2 = "ref/$file1" unless $file2;
	$file1 = $Initfour::Backoffice::prefix . $file1;
	my ($str1, $str2);
	local($/);
	open(my $fd1, "<:encoding(utf-8)", $file1) or die("$file1: $!\n");
	$str1 = <$fd1>;
	close($fd1);
	open(my $fd2, "<:encoding(utf-8)", $file2) or die("$file2: $!\n");
	$str2 = <$fd2>;
	close($fd2);
	$str1 =~ s/generated by the InitFour backoffice on.*//mi;
	$str2 =~ s/generated by the InitFour backoffice on.*//mi;

	$str1 =~ s/Last zone update: .*//m;
	$str2 =~ s/Last zone update: .*//m;
	return 0 if $str1 eq $str2;
	1;
}


1;
